# -*- coding: utf-8 -*-
"""Essensial Python for DA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNIiBJNfU1WD4ZPo9FyMVtvClkgzN7dA

# **Essential Python For DA**

## **OOP**
"""

class Dog:
    def __init__(self, name, species, age):
        self.name = name
        self.species = species
        self.age = age

    def bark(self):
        print(f"{self.name} is barking 'hong hong")

    def hbd(self):
        self.age += 1

## attributes
dog1 = Dog("milo", "Chihuahua", 2)

dog2 = Dog("david", "Husky",3)

print(f"{dog1.name} is {dog1.species}")
print(f"{dog2.name} is {dog2.species}")

dog1.bark()

dog2.bark()

print(dog1.age)
dog1.hbd()
print(dog1.age)

## homework

#สร้าง OOP ตู้ ATM 5 function
##deposit, withdraw, check balance, OTP, order coffee , pay bill, internet etc.

class ATM:
    def __init__(self, username, blank, amount):
        self.username = username
        self.blank = blank
        self.amount = amount

        def check_balance(self):
            print(f"Balance : {self.amount} THB.")

        def deposit(self, saving):
            self.amount += saving
            print(f"Deposit {saving} THB successfully")

toy = ATM("kasidis toy", "scb", 100)

toy.check_balance()

"""## **Try Except Block**"""

try:
    result =1/0
except :
    print("this is an error message")

!pwd

!ls

!cat hotel.csv

## read file
import csv

try:
    file = open('hotel.csv', 'r') # r w a

    data = csv.reader(file)

    for row in data:
        print(row)

    file.close()
except FileNotFoundError:
    print("file not found, please check filename again.")
finally:
    print("read file successfully")

# context manager
read_data = []
with open('hotel.csv', 'r') as file:
    data = csv.reader(file)
    for row in data:
        read_data.append(row)

read_data

read_data[0]

read_data[1:]

## for loop to calculate avg. price per night
prices = []

for row in read_data[1: ]:
    prices.append(int(row[-1]))

print(f"Average price per night: {sum(prices)/ len(prices)}")

## modern python
import pandas as pd

df= pd.read_csv("hotel.csv")

df.head()

"""## Read & Write Files"""

import csv

head = ['id', 'name', 'city']
body = [
    [1, "CU", "Bangkok"],
    [2, "LSK", "London"],
    [3, "Reading", "Reading"]
]

with open('school.csv', 'w') as file:
    writer = csv.writer(file)
    writer.writerow(head)
    writer.writerows(body)

ls

!cat school.csv

# modern python
import pandas as pd

df = pd.read_csv('school.csv')

df.to_csv('school2.csv')

!ls

!cat school2.csv

#read data from interner

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/penguins.csv"

import pandas as pd

df_penguin = pd.read_csv(url)

df_penguin.head()

## select column
df_penguin[["species", "island", "body_mass_g"]].head(10)

## filter rows
df_penguin[["species", "island", "body_mass_g"]]\
    .query("species == 'Adelie' and island == 'Dream' ")\
    .head(10)

## filter without query()
df_penguin[df_penguin['body_mass_g'] >= 4500]

"""## Request

How to get data via API the easy way
"""

import requests

## api endpoint
url = "https://swapi.info/api/people/1"

response = requests.get(url)

response.json()

response.json()['height']

## for loop
import requests
import time

characters = []
for i in range(5):
    url = f"https://swapi.info/api/people/{i+1}"
    response = requests.get(url)
    response_json = response.json()
    data = [response_json["name"],
            response_json["height"],
            response_json["mass"]]
    characters.append(data)
    print(f"Success: {i+1}")
    time.sleep(1)
print(characters)

import pandas as pd

starwars = pd.DataFrame(characters, columns = ["name", "height", "mass"])

starwars

## homework public api